### ISSUE TITLE
init-présentation

### ISSUE THREAD

**Issue by essarraj-fouad** [labs-web/lab-poo#25]
# init-présentation

## Travail à faire
- Élaboration d'un presentation sans contenu avec les pages et leurs titres
- Ajouter le lien de presentation dans readme.md

## Livrable

- backlog/sous-tâche/2.init-presentation.24.md
- docs/*
- README.md
- README.json

**Comment by essarraj-fouad** [comment]
- la description de la tâche n'est pas valide
  - Le livrable n'est pas valide

**Comment by zaani12** [comment]
- le résultat n'est pas conforme au livrables dans la description de l'issue

**Comment by husseinbouik** [comment]
- le pullrequest a une conflit

**Comment by redagrain** [comment]
> * le pullrequest a une conflit

fixed
